import { GameWithoutIdentifiers } from "../../lib/definitions";

export const games: GameWithoutIdentifiers[] = [
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Allegiant Stadium, Las Vegas",
    datetime: "2024-03-02T13:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Sydney Roosters",
    away_team_name: "Brisbane Broncos",
    venue: "Allegiant Stadium, Las Vegas",
    datetime: "2024-03-02T16:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Newcastle Knights",
    away_team_name: "Canberra Raiders",
    venue: "McDonald Jones Stadium",
    datetime: "2024-03-08T19:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Melbourne Storm",
    away_team_name: "Penrith Panthers",
    venue: "AAMI Park",
    datetime: "2024-03-08T19:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Parramatta Eels",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "CommBank Stadium",
    datetime: "2024-03-09T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Dolphins",
    away_team_name: "North Queensland Cowboys",
    venue: "Suncorp Stadium",
    datetime: "2024-03-10T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Brisbane Broncos",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Suncorp Stadium",
    datetime: "2024-03-14T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Penrith Panthers",
    away_team_name: "Parramatta Eels",
    venue: "BlueBet Stadium",
    datetime: "2024-03-15T19:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Cronulla Sharks",
    away_team_name: "North Queensland Cowboys",
    venue: "PointsBet Stadium",
    datetime: "2024-03-15T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Newcastle Knights",
    venue: "4 Pines Park",
    datetime: "2024-03-16T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Wests Tigers",
    venue: "Cbus Super Stadium",
    datetime: "2024-03-16T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Melbourne Storm",
    away_team_name: "Sydney Roosters",
    venue: "AAMI Park",
    datetime: "2024-03-16T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Canberra Raiders",
    away_team_name: "Dolphins",
    venue: "GIO Stadium",
    datetime: "2024-03-17T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Mt Smart Stadium",
    datetime: "2024-03-17T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  // Continue with remaining rounds and games...
];
