import { GameWithoutIdentifiers } from "../../lib/definitions";

export const games: GameWithoutIdentifiers[] = [
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Allegiant Stadium, Las Vegas",
    datetime: "2024-03-02T13:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Sydney Roosters",
    away_team_name: "Brisbane Broncos",
    venue: "Allegiant Stadium, Las Vegas",
    datetime: "2024-03-02T16:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Newcastle Knights",
    away_team_name: "Canberra Raiders",
    venue: "McDonald Jones Stadium",
    datetime: "2024-03-08T19:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Melbourne Storm",
    away_team_name: "Penrith Panthers",
    venue: "AAMI Park",
    datetime: "2024-03-08T19:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Parramatta Eels",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "CommBank Stadium",
    datetime: "2024-03-09T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "1",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "North Queensland Cowboys",
    venue: "Suncorp Stadium",
    datetime: "2024-03-10T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Brisbane Broncos",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Suncorp Stadium",
    datetime: "2024-03-14T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Penrith Panthers",
    away_team_name: "Parramatta Eels",
    venue: "BlueBet Stadium",
    datetime: "2024-03-15T19:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Cronulla Sharks",
    away_team_name: "North Queensland Cowboys",
    venue: "PointsBet Stadium",
    datetime: "2024-03-15T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Newcastle Knights",
    venue: "4 Pines Park",
    datetime: "2024-03-16T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Wests Tigers",
    venue: "Cbus Super Stadium",
    datetime: "2024-03-16T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Melbourne Storm",
    away_team_name: "Sydney Roosters",
    venue: "AAMI Park",
    datetime: "2024-03-16T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "Canberra Raiders",
    away_team_name: "Redcliffe Dolphins",
    venue: "GIO Stadium",
    datetime: "2024-03-17T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "2",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Mt Smart Stadium",
    datetime: "2024-03-17T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Gold Coast Titans",
    venue: "Stadium Australia",
    datetime: "2024-03-21T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "Sydney Roosters",
    away_team_name: "Parramatta Eels",
    venue: "Allianz Stadium",
    datetime: "2024-03-22T19:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "Brisbane Broncos",
    away_team_name: "St. George Illawarra Dragons",
    venue: "Suncorp Stadium",
    datetime: "2024-03-22T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "Canberra Raiders",
    away_team_name: "Penrith Panthers",
    venue: "GIO Stadium",
    datetime: "2024-03-23T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Melbourne Storm",
    venue: "PointsBet Stadium",
    datetime: "2024-03-23T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "Newcastle Knights",
    away_team_name: "New Zealand Warriors",
    venue: "McDonald Jones Stadium",
    datetime: "2024-03-23T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "Wests Tigers",
    away_team_name: "North Queensland Cowboys",
    venue: "Leichhardt Oval",
    datetime: "2024-03-24T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "3",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "4 Pines Park",
    datetime: "2024-03-24T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "4",
    home_team_name: "Parramatta Eels",
    away_team_name: "Brisbane Broncos",
    venue: "CommBank Stadium",
    datetime: "2024-03-28T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "4",
    home_team_name: "Melbourne Storm",
    away_team_name: "South Sydney Rabbitohs",
    venue: "AAMI Park",
    datetime: "2024-03-29T19:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "4",
    home_team_name: "Penrith Panthers",
    away_team_name: "Canberra Raiders",
    venue: "BlueBet Stadium",
    datetime: "2024-03-29T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "4",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Cronulla Sharks",
    venue: "Mt Smart Stadium",
    datetime: "2024-03-30T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "4",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Melbourne Storm",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-03-30T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "4",
    home_team_name: "Newcastle Knights",
    away_team_name: "Sydney Roosters",
    venue: "McDonald Jones Stadium",
    datetime: "2024-03-30T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "4",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Redcliffe Dolphins",
    venue: "Cbus Super Stadium",
    datetime: "2024-03-31T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "4",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Manly Sea Eagles",
    venue: "Accor Stadium",
    datetime: "2024-03-31T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Sydney Roosters",
    venue: "Stadium Australia",
    datetime: "2024-04-04T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Canberra Raiders",
    venue: "Mt Smart Stadium",
    datetime: "2024-04-05T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "Melbourne Storm",
    away_team_name: "Cronulla Sharks",
    venue: "AAMI Park",
    datetime: "2024-04-05T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "Penrith Panthers",
    away_team_name: "Manly Sea Eagles",
    venue: "BlueBet Stadium",
    datetime: "2024-04-06T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Newcastle Knights",
    venue: "Cbus Super Stadium",
    datetime: "2024-04-06T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Parramatta Eels",
    venue: "Suncorp Stadium",
    datetime: "2024-04-06T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Wests Tigers",
    venue: "Suncorp Stadium",
    datetime: "2024-04-07T14:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "5",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-04-07T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "6",
    home_team_name: "Sydney Roosters",
    away_team_name: "Melbourne Storm",
    venue: "Allianz Stadium",
    datetime: "2024-04-11T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "6",
    home_team_name: "Canberra Raiders",
    away_team_name: "South Sydney Rabbitohs",
    venue: "GIO Stadium",
    datetime: "2024-04-12T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "6",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Penrith Panthers",
    venue: "PointsBet Stadium",
    datetime: "2024-04-12T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "6",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Redcliffe Dolphins",
    venue: "4 Pines Park",
    datetime: "2024-04-13T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "6",
    home_team_name: "Newcastle Knights",
    away_team_name: "North Queensland Cowboys",
    venue: "McDonald Jones Stadium",
    datetime: "2024-04-13T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "6",
    home_team_name: "Parramatta Eels",
    away_team_name: "Gold Coast Titans",
    venue: "CommBank Stadium",
    datetime: "2024-04-13T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "6",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Brisbane Broncos",
    venue: "Accor Stadium",
    datetime: "2024-04-14T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "6",
    home_team_name: "Wests Tigers",
    away_team_name: "New Zealand Warriors",
    venue: "Leichhardt Oval",
    datetime: "2024-04-14T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "Melbourne Storm",
    away_team_name: "New Zealand Warriors",
    venue: "AAMI Park",
    datetime: "2024-04-18T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Stadium Australia",
    datetime: "2024-04-19T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Sydney Roosters",
    venue: "PointsBet Stadium",
    datetime: "2024-04-19T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Parramatta Eels",
    venue: "Cbus Super Stadium",
    datetime: "2024-04-20T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Newcastle Knights",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-04-20T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Canberra Raiders",
    venue: "4 Pines Park",
    datetime: "2024-04-20T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Wests Tigers",
    venue: "Suncorp Stadium",
    datetime: "2024-04-21T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "7",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Penrith Panthers",
    venue: "Suncorp Stadium",
    datetime: "2024-04-21T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "8",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Cronulla Sharks",
    venue: "Accor Stadium",
    datetime: "2024-04-25T14:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "8",
    home_team_name: "Parramatta Eels",
    away_team_name: "Melbourne Storm",
    venue: "CommBank Stadium",
    datetime: "2024-04-25T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "8",
    home_team_name: "Sydney Roosters",
    away_team_name: "Redcliffe Dolphins",
    venue: "Allianz Stadium",
    datetime: "2024-04-25T18:10:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "8",
    home_team_name: "Penrith Panthers",
    away_team_name: "South Sydney Rabbitohs",
    venue: "BlueBet Stadium",
    datetime: "2024-04-26T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "8",
    home_team_name: "Gold Coast Titans",
    away_team_name: "North Queensland Cowboys",
    venue: "Cbus Super Stadium",
    datetime: "2024-04-27T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "8",
    home_team_name: "Newcastle Knights",
    away_team_name: "Brisbane Broncos",
    venue: "McDonald Jones Stadium",
    datetime: "2024-04-27T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "8",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "New Zealand Warriors",
    venue: "4 Pines Park",
    datetime: "2024-04-27T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "8",
    home_team_name: "Canberra Raiders",
    away_team_name: "Wests Tigers",
    venue: "GIO Stadium",
    datetime: "2024-04-28T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Brisbane Broncos",
    venue: "PointsBet Stadium",
    datetime: "2024-05-02T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "Canberra Raiders",
    away_team_name: "Parramatta Eels",
    venue: "GIO Stadium",
    datetime: "2024-05-03T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Melbourne Storm",
    venue: "Stadium Australia",
    datetime: "2024-05-03T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Manly Sea Eagles",
    venue: "Mt Smart Stadium",
    datetime: "2024-05-04T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "Penrith Panthers",
    away_team_name: "Sydney Roosters",
    venue: "BlueBet Stadium",
    datetime: "2024-05-04T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Redcliffe Dolphins",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-05-04T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Cbus Super Stadium",
    datetime: "2024-05-05T14:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "9",
    home_team_name: "Wests Tigers",
    away_team_name: "Newcastle Knights",
    venue: "Leichhardt Oval",
    datetime: "2024-05-05T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "10",
    home_team_name: "Melbourne Storm",
    away_team_name: "Cronulla Sharks",
    venue: "AAMI Park",
    datetime: "2024-05-09T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "10",
    home_team_name: "Canberra Raiders",
    away_team_name: "South Sydney Rabbitohs",
    venue: "GIO Stadium",
    datetime: "2024-05-10T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "10",
    home_team_name: "Parramatta Eels",
    away_team_name: "Penrith Panthers",
    venue: "CommBank Stadium",
    datetime: "2024-05-10T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "10",
    home_team_name: "Newcastle Knights",
    away_team_name: "Gold Coast Titans",
    venue: "McDonald Jones Stadium",
    datetime: "2024-05-11T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "10",
    home_team_name: "Sydney Roosters",
    away_team_name: "Redcliffe Dolphins",
    venue: "Allianz Stadium",
    datetime: "2024-05-11T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "10",
    home_team_name: "Brisbane Broncos",
    away_team_name: "North Queensland Cowboys",
    venue: "Suncorp Stadium",
    datetime: "2024-05-11T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "10",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Wests Tigers",
    venue: "4 Pines Park",
    datetime: "2024-05-12T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "10",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "New Zealand Warriors",
    venue: "Accor Stadium",
    datetime: "2024-05-12T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Parramatta Eels",
    venue: "Stadium Australia",
    datetime: "2024-05-16T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Canberra Raiders",
    venue: "Accor Stadium",
    datetime: "2024-05-17T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Melbourne Storm",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-05-17T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Gold Coast Titans",
    venue: "PointsBet Stadium",
    datetime: "2024-05-18T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "Newcastle Knights",
    away_team_name: "Manly Sea Eagles",
    venue: "McDonald Jones Stadium",
    datetime: "2024-05-18T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "Penrith Panthers",
    away_team_name: "Sydney Roosters",
    venue: "BlueBet Stadium",
    datetime: "2024-05-18T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Brisbane Broncos",
    venue: "Suncorp Stadium",
    datetime: "2024-05-19T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "11",
    home_team_name: "Wests Tigers",
    away_team_name: "New Zealand Warriors",
    venue: "Leichhardt Oval",
    datetime: "2024-05-19T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "12",
    home_team_name: "Sydney Roosters",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Allianz Stadium",
    datetime: "2024-05-23T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "12",
    home_team_name: "Gold Coast Titans",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Cbus Super Stadium",
    datetime: "2024-05-24T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "12",
    home_team_name: "Melbourne Storm",
    away_team_name: "Cronulla Sharks",
    venue: "AAMI Park",
    datetime: "2024-05-24T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "12",
    home_team_name: "Penrith Panthers",
    away_team_name: "Newcastle Knights",
    venue: "BlueBet Stadium",
    datetime: "2024-05-25T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "12",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "North Queensland Cowboys",
    venue: "4 Pines Park",
    datetime: "2024-05-25T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "12",
    home_team_name: "Canberra Raiders",
    away_team_name: "Brisbane Broncos",
    venue: "GIO Stadium",
    datetime: "2024-05-25T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "12",
    home_team_name: "Parramatta Eels",
    away_team_name: "Wests Tigers",
    venue: "CommBank Stadium",
    datetime: "2024-05-26T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "12",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Redcliffe Dolphins",
    venue: "Mt Smart Stadium",
    datetime: "2024-05-26T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "Canberra Raiders",
    away_team_name: "North Queensland Cowboys",
    venue: "GIO Stadium",
    datetime: "2024-05-30T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Melbourne Storm",
    venue: "Cbus Super Stadium",
    datetime: "2024-05-31T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "Parramatta Eels",
    away_team_name: "South Sydney Rabbitohs",
    venue: "CommBank Stadium",
    datetime: "2024-05-31T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Newcastle Knights",
    venue: "PointsBet Stadium",
    datetime: "2024-06-01T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "Wests Tigers",
    away_team_name: "Penrith Panthers",
    venue: "Leichhardt Oval",
    datetime: "2024-06-01T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "Sydney Roosters",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Allianz Stadium",
    datetime: "2024-06-01T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Redcliffe Dolphins",
    venue: "Suncorp Stadium",
    datetime: "2024-06-02T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "13",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Manly Sea Eagles",
    venue: "Mt Smart Stadium",
    datetime: "2024-06-02T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "14",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Parramatta Eels",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-06-06T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "14",
    home_team_name: "Melbourne Storm",
    away_team_name: "Cronulla Sharks",
    venue: "AAMI Park",
    datetime: "2024-06-07T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "14",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Gold Coast Titans",
    venue: "Stadium Australia",
    datetime: "2024-06-07T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "14",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Brisbane Broncos",
    venue: "Accor Stadium",
    datetime: "2024-06-08T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "14",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Sydney Roosters",
    venue: "4 Pines Park",
    datetime: "2024-06-08T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "14",
    home_team_name: "Newcastle Knights",
    away_team_name: "Wests Tigers",
    venue: "McDonald Jones Stadium",
    datetime: "2024-06-08T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "14",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "New Zealand Warriors",
    venue: "Suncorp Stadium",
    datetime: "2024-06-09T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "14",
    home_team_name: "Penrith Panthers",
    away_team_name: "Canberra Raiders",
    venue: "BlueBet Stadium",
    datetime: "2024-06-09T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Parramatta Eels",
    venue: "PointsBet Stadium",
    datetime: "2024-06-13T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "Melbourne Storm",
    away_team_name: "Penrith Panthers",
    venue: "AAMI Park",
    datetime: "2024-06-14T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "Sydney Roosters",
    away_team_name: "Canberra Raiders",
    venue: "Allianz Stadium",
    datetime: "2024-06-14T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Manly Sea Eagles",
    venue: "Stadium Australia",
    datetime: "2024-06-15T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "Newcastle Knights",
    away_team_name: "Gold Coast Titans",
    venue: "McDonald Jones Stadium",
    datetime: "2024-06-15T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Brisbane Broncos",
    venue: "Suncorp Stadium",
    datetime: "2024-06-15T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Wests Tigers",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-06-16T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "15",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "New Zealand Warriors",
    venue: "Accor Stadium",
    datetime: "2024-06-16T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "16",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Melbourne Storm",
    venue: "Suncorp Stadium",
    datetime: "2024-06-20T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "16",
    home_team_name: "Parramatta Eels",
    away_team_name: "Gold Coast Titans",
    venue: "CommBank Stadium",
    datetime: "2024-06-21T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "16",
    home_team_name: "Sydney Roosters",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Allianz Stadium",
    datetime: "2024-06-21T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "16",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Newcastle Knights",
    venue: "PointsBet Stadium",
    datetime: "2024-06-22T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "16",
    home_team_name: "Penrith Panthers",
    away_team_name: "Canberra Raiders",
    venue: "BlueBet Stadium",
    datetime: "2024-06-22T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "16",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Redcliffe Dolphins",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-06-22T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "16",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "4 Pines Park",
    datetime: "2024-06-23T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "16",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Wests Tigers",
    venue: "Mt Smart Stadium",
    datetime: "2024-06-23T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "NRL",
    round: "17",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Penrith Panthers",
    venue: "Stadium Australia",
    datetime: "2024-06-27T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "17",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Cronulla Sharks",
    venue: "Cbus Super Stadium",
    datetime: "2024-06-28T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "17",
    home_team_name: "Canberra Raiders",
    away_team_name: "Melbourne Storm",
    venue: "GIO Stadium",
    datetime: "2024-06-28T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "17",
    home_team_name: "Sydney Roosters",
    away_team_name: "Brisbane Broncos",
    venue: "Allianz Stadium",
    datetime: "2024-06-29T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "17",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "North Queensland Cowboys",
    venue: "4 Pines Park",
    datetime: "2024-06-29T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "17",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Parramatta Eels",
    venue: "Suncorp Stadium",
    datetime: "2024-06-29T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "17",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Newcastle Knights",
    venue: "Mt Smart Stadium",
    datetime: "2024-06-30T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "17",
    home_team_name: "Wests Tigers",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Leichhardt Oval",
    datetime: "2024-06-30T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Parramatta Eels",
    away_team_name: "Sydney Roosters",
    venue: "CommBank Stadium",
    datetime: "2024-07-04T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Gold Coast Titans",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Cbus Super Stadium",
    datetime: "2024-07-05T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Canberra Raiders",
    away_team_name: "New Zealand Warriors",
    venue: "GIO Stadium",
    datetime: "2024-07-05T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Newcastle Knights",
    away_team_name: "Cronulla Sharks",
    venue: "McDonald Jones Stadium",
    datetime: "2024-07-06T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Melbourne Storm",
    venue: "Suncorp Stadium",
    datetime: "2024-07-06T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "North Queensland Cowboys",
    venue: "4 Pines Park",
    datetime: "2024-07-06T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Wests Tigers",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Leichhardt Oval",
    datetime: "2024-07-07T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "18",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Penrith Panthers",
    venue: "Suncorp Stadium",
    datetime: "2024-07-07T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Newcastle Knights",
    venue: "Stadium Australia",
    datetime: "2024-07-11T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "Gold Coast Titans",
    away_team_name: "North Queensland Cowboys",
    venue: "Cbus Super Stadium",
    datetime: "2024-07-12T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "Canberra Raiders",
    away_team_name: "Brisbane Broncos",
    venue: "GIO Stadium",
    datetime: "2024-07-12T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Wests Tigers",
    venue: "PointsBet Stadium",
    datetime: "2024-07-13T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "Melbourne Storm",
    away_team_name: "Sydney Roosters",
    venue: "AAMI Park",
    datetime: "2024-07-13T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Parramatta Eels",
    venue: "4 Pines Park",
    datetime: "2024-07-13T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "New Zealand Warriors",
    venue: "Suncorp Stadium",
    datetime: "2024-07-14T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "19",
    home_team_name: "Penrith Panthers",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "BlueBet Stadium",
    datetime: "2024-07-14T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "Sydney Roosters",
    away_team_name: "Canberra Raiders",
    venue: "Allianz Stadium",
    datetime: "2024-07-18T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "Newcastle Knights",
    away_team_name: "Gold Coast Titans",
    venue: "McDonald Jones Stadium",
    datetime: "2024-07-19T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "Melbourne Storm",
    away_team_name: "Cronulla Sharks",
    venue: "AAMI Park",
    datetime: "2024-07-19T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Manly Sea Eagles",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-07-20T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "Wests Tigers",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Leichhardt Oval",
    datetime: "2024-07-20T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "Parramatta Eels",
    away_team_name: "Redcliffe Dolphins",
    venue: "CommBank Stadium",
    datetime: "2024-07-20T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Penrith Panthers",
    venue: "Suncorp Stadium",
    datetime: "2024-07-21T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "20",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "New Zealand Warriors",
    venue: "Accor Stadium",
    datetime: "2024-07-21T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "Melbourne Storm",
    away_team_name: "North Queensland Cowboys",
    venue: "AAMI Park",
    datetime: "2024-07-25T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Sydney Roosters",
    venue: "Cbus Super Stadium",
    datetime: "2024-07-26T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "Penrith Panthers",
    away_team_name: "South Sydney Rabbitohs",
    venue: "BlueBet Stadium",
    datetime: "2024-07-26T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "Newcastle Knights",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "McDonald Jones Stadium",
    datetime: "2024-07-27T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Parramatta Eels",
    venue: "Suncorp Stadium",
    datetime: "2024-07-27T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Wests Tigers",
    venue: "PointsBet Stadium",
    datetime: "2024-07-27T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Redcliffe Dolphins",
    venue: "4 Pines Park",
    datetime: "2024-07-28T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "21",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Canberra Raiders",
    venue: "Mt Smart Stadium",
    datetime: "2024-07-28T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Brisbane Broncos",
    venue: "Stadium Australia",
    datetime: "2024-08-01T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "Canberra Raiders",
    away_team_name: "Gold Coast Titans",
    venue: "GIO Stadium",
    datetime: "2024-08-02T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "Sydney Roosters",
    away_team_name: "Manly Sea Eagles",
    venue: "Allianz Stadium",
    datetime: "2024-08-02T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Melbourne Storm",
    venue: "Mt Smart Stadium",
    datetime: "2024-08-03T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Penrith Panthers",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-08-03T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Redcliffe Dolphins",
    venue: "PointsBet Stadium",
    datetime: "2024-08-03T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "Wests Tigers",
    away_team_name: "Parramatta Eels",
    venue: "Leichhardt Oval",
    datetime: "2024-08-04T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "22",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Newcastle Knights",
    venue: "Accor Stadium",
    datetime: "2024-08-04T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "Melbourne Storm",
    away_team_name: "Sydney Roosters",
    venue: "AAMI Park",
    datetime: "2024-08-08T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Gold Coast Titans",
    venue: "Mt Smart Stadium",
    datetime: "2024-08-09T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "Brisbane Broncos",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Suncorp Stadium",
    datetime: "2024-08-09T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Canberra Raiders",
    venue: "Suncorp Stadium",
    datetime: "2024-08-10T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "Penrith Panthers",
    away_team_name: "Manly Sea Eagles",
    venue: "BlueBet Stadium",
    datetime: "2024-08-10T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "Parramatta Eels",
    away_team_name: "Cronulla Sharks",
    venue: "CommBank Stadium",
    datetime: "2024-08-10T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-08-11T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "23",
    home_team_name: "Newcastle Knights",
    away_team_name: "Wests Tigers",
    venue: "McDonald Jones Stadium",
    datetime: "2024-08-11T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Melbourne Storm",
    venue: "Stadium Australia",
    datetime: "2024-08-15T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "Canberra Raiders",
    away_team_name: "Penrith Panthers",
    venue: "GIO Stadium",
    datetime: "2024-08-16T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "Cronulla Sharks",
    away_team_name: "North Queensland Cowboys",
    venue: "PointsBet Stadium",
    datetime: "2024-08-16T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "Sydney Roosters",
    away_team_name: "New Zealand Warriors",
    venue: "Allianz Stadium",
    datetime: "2024-08-17T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Brisbane Broncos",
    venue: "Cbus Super Stadium",
    datetime: "2024-08-17T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "4 Pines Park",
    datetime: "2024-08-17T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Wests Tigers",
    venue: "Suncorp Stadium",
    datetime: "2024-08-18T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "24",
    home_team_name: "Parramatta Eels",
    away_team_name: "Newcastle Knights",
    venue: "CommBank Stadium",
    datetime: "2024-08-18T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "Melbourne Storm",
    away_team_name: "Sydney Roosters",
    venue: "AAMI Park",
    datetime: "2024-08-22T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "Canberra Raiders",
    away_team_name: "North Queensland Cowboys",
    venue: "GIO Stadium",
    datetime: "2024-08-23T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Gold Coast Titans",
    venue: "4 Pines Park",
    datetime: "2024-08-23T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "Newcastle Knights",
    away_team_name: "Canterbury-Bankstown Bulldogs",
    venue: "McDonald Jones Stadium",
    datetime: "2024-08-24T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "Parramatta Eels",
    away_team_name: "South Sydney Rabbitohs",
    venue: "CommBank Stadium",
    datetime: "2024-08-24T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "Cronulla Sharks",
    away_team_name: "Brisbane Broncos",
    venue: "PointsBet Stadium",
    datetime: "2024-08-24T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "Penrith Panthers",
    away_team_name: "Wests Tigers",
    venue: "BlueBet Stadium",
    datetime: "2024-08-25T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "25",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Redcliffe Dolphins",
    venue: "Mt Smart Stadium",
    datetime: "2024-08-25T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "South Sydney Rabbitohs",
    away_team_name: "Cronulla Sharks",
    venue: "Stadium Australia",
    datetime: "2024-08-29T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "Melbourne Storm",
    away_team_name: "Penrith Panthers",
    venue: "AAMI Park",
    datetime: "2024-08-30T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "North Queensland Cowboys",
    away_team_name: "Sydney Roosters",
    venue: "Queensland Country Bank Stadium",
    datetime: "2024-08-30T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "Gold Coast Titans",
    away_team_name: "Newcastle Knights",
    venue: "Cbus Super Stadium",
    datetime: "2024-08-31T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Parramatta Eels",
    venue: "Suncorp Stadium",
    datetime: "2024-08-31T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Wests Tigers",
    venue: "Accor Stadium",
    datetime: "2024-08-31T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Manly Sea Eagles",
    venue: "Suncorp Stadium",
    datetime: "2024-09-01T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "26",
    home_team_name: "Canberra Raiders",
    away_team_name: "New Zealand Warriors",
    venue: "GIO Stadium",
    datetime: "2024-09-01T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "Sydney Roosters",
    away_team_name: "South Sydney Rabbitohs",
    venue: "Allianz Stadium",
    datetime: "2024-09-05T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "New Zealand Warriors",
    away_team_name: "Gold Coast Titans",
    venue: "Mt Smart Stadium",
    datetime: "2024-09-06T18:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "Brisbane Broncos",
    away_team_name: "Melbourne Storm",
    venue: "Suncorp Stadium",
    datetime: "2024-09-06T20:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "Redcliffe Dolphins",
    away_team_name: "Cronulla Sharks",
    venue: "Suncorp Stadium",
    datetime: "2024-09-07T15:00:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "Penrith Panthers",
    away_team_name: "North Queensland Cowboys",
    venue: "BlueBet Stadium",
    datetime: "2024-09-07T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "Parramatta Eels",
    away_team_name: "Canberra Raiders",
    venue: "CommBank Stadium",
    datetime: "2024-09-07T19:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "Manly Sea Eagles",
    away_team_name: "Wests Tigers",
    venue: "4 Pines Park",
    datetime: "2024-09-08T16:05:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "NRL",
    round: "27",
    home_team_name: "Canterbury-Bankstown Bulldogs",
    away_team_name: "Newcastle Knights",
    venue: "Accor Stadium",
    datetime: "2024-09-08T18:15:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "19",
    home_team_name: "Essendon Bombers",
    away_team_name: "Western Bulldogs",
    venue: "Marvel Stadium",
    datetime: "2024-07-19T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "19",
    home_team_name: "Richmond Tigers",
    away_team_name: "Hawthorn Hawks",
    venue: "MCG",
    datetime: "2024-07-20T13:45:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "19",
    home_team_name: "Geelong Cats",
    away_team_name: "Fremantle Dockers",
    venue: "GMHBA Stadium",
    datetime: "2024-07-20T16:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "19",
    home_team_name: "Sydney Swans",
    away_team_name: "Carlton Blues",
    venue: "SCG",
    datetime: "2024-07-20T19:25:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "19",
    home_team_name: "Brisbane Lions",
    away_team_name: "Gold Coast Suns",
    venue: "Gabba",
    datetime: "2024-07-21T13:10:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "19",
    home_team_name: "Melbourne Demons",
    away_team_name: "St Kilda Saints",
    venue: "MCG",
    datetime: "2024-07-21T15:20:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "19",
    home_team_name: "Port Adelaide Power",
    away_team_name: "Adelaide Crows",
    venue: "Adelaide Oval",
    datetime: "2024-07-21T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "AFL",
    round: "20",
    home_team_name: "Western Bulldogs",
    away_team_name: "Sydney Swans",
    venue: "Marvel Stadium",
    datetime: "2024-07-26T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "20",
    home_team_name: "Carlton Blues",
    away_team_name: "Collingwood Magpies",
    venue: "MCG",
    datetime: "2024-07-27T13:45:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "20",
    home_team_name: "Gold Coast Suns",
    away_team_name: "Richmond Tigers",
    venue: "Metricon Stadium",
    datetime: "2024-07-27T16:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "20",
    home_team_name: "St Kilda Saints",
    away_team_name: "Geelong Cats",
    venue: "Marvel Stadium",
    datetime: "2024-07-27T19:25:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "20",
    home_team_name: "Adelaide Crows",
    away_team_name: "West Coast Eagles",
    venue: "Adelaide Oval",
    datetime: "2024-07-28T13:10:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "20",
    home_team_name: "GWS Giants",
    away_team_name: "Brisbane Lions",
    venue: "GIANTS Stadium",
    datetime: "2024-07-28T15:20:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "20",
    home_team_name: "Hawthorn Hawks",
    away_team_name: "Melbourne Demons",
    venue: "MCG",
    datetime: "2024-07-28T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },

  {
    sport: "AFL",
    round: "21",
    home_team_name: "Collingwood Magpies",
    away_team_name: "Port Adelaide Power",
    venue: "MCG",
    datetime: "2024-08-02T19:50:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "21",
    home_team_name: "Fremantle Dockers",
    away_team_name: "Carlton Blues",
    venue: "Optus Stadium",
    datetime: "2024-08-03T14:10:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "21",
    home_team_name: "Western Bulldogs",
    away_team_name: "GWS Giants",
    venue: "Marvel Stadium",
    datetime: "2024-08-03T16:35:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "21",
    home_team_name: "Sydney Swans",
    away_team_name: "Hawthorn Hawks",
    venue: "SCG",
    datetime: "2024-08-03T19:25:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "21",
    home_team_name: "Richmond Tigers",
    away_team_name: "Brisbane Lions",
    venue: "MCG",
    datetime: "2024-08-04T13:10:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "21",
    home_team_name: "St Kilda Saints",
    away_team_name: "Adelaide Crows",
    venue: "Marvel Stadium",
    datetime: "2024-08-04T15:20:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
  {
    sport: "AFL",
    round: "21",
    home_team_name: "West Coast Eagles",
    away_team_name: "Essendon Bombers",
    venue: "Optus Stadium",
    datetime: "2024-08-04T17:30:00+10:00",
    season: "2024",
    winning_team_id: null,
    status: "upcoming",
  },
];
